services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - ./_data/logs/elasticsearch:/usr/share/elasticsearch/data
    restart: always
    labels:
      - insidiae.project=Insidiae
      - insidiae.pool=Elasticsearch
      - insidiae.type=pool_service
      - insidiae.session=939b5024
    networks:
      - elasticsearch_net
  elasticsearch_kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    restart: always
    labels:
      - insidiae.project=Insidiae
      - insidiae.pool=Elasticsearch
      - insidiae.type=pool_service
      - insidiae.session=939b5024
    networks:
      - elasticsearch_net
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    volumes:
      - ./_data/logs/elasticsearch/suricata:/var/log/suricata
      - ./_data/configs/elasticsearch/suricata:/etc/suricata
      - ./_data/configs/elasticsearch/suricata/rules:/var/lib/suricata/rules
    restart: always
    depends_on:
      - elasticsearch
    labels:
      - insidiae.project=Insidiae
      - insidiae.pool=Elasticsearch
      - insidiae.type=collector
      - insidiae.collector=Suricata
      - insidiae.session=939b5024
    networks:
      - elasticsearch_net
  zeek:
    image: zeek/zeek:latest
    container_name: zeek
    volumes:
      - ./_data/logs/elasticsearch/zeek:/var/log/zeek
    restart: always
    depends_on:
      - elasticsearch
    labels:
      - insidiae.project=Insidiae
      - insidiae.pool=Elasticsearch
      - insidiae.type=collector
      - insidiae.collector=Zeek
      - insidiae.session=939b5024
    networks:
      - elasticsearch_net
version: '3.8'
networks:
  elasticsearch_net:
    driver: bridge
